/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "DistributedFeatureExtraction"
 */
package DistributedFeatureExtraction;

import java.io.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;

public class AlgorithmParametersAsn {

	@Component(0)
	public ParametersAsn detectionparameters;

	@Component(1)
	public ParametersAsn extractionparameters;


	public boolean equals(Object obj) {
		if(!(obj instanceof AlgorithmParametersAsn)){
			return false;
		}
		return TYPE.equals(this, obj, CONVERTER);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONVERTER, out);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONVERTER, out);
	}

	public static AlgorithmParametersAsn der_decode(InputStream in) throws IOException {
		return (AlgorithmParametersAsn)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONVERTER);
	}


	public final static AsnType TYPE = DistributedFeatureExtraction.type(65539);

	public final static CompositeConverter CONVERTER;

	static {
		CONVERTER = new AnnotationCompositeConverter(AlgorithmParametersAsn.class);
		AsnConverter detectionparametersConverter = ParametersAsn.CONVERTER;
		AsnConverter extractionparametersConverter = ParametersAsn.CONVERTER;
		CONVERTER.setComponentConverters(new AsnConverter[] { detectionparametersConverter, extractionparametersConverter });
	}


}
