/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "DistributedFeatureExtraction"
 */
package DistributedFeatureExtraction;

import java.io.*;
import java.util.Vector;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;

public class CompletedTasksAsn {

	@Component(0)
	public Vector<ImgTaskAsn> imgtasks;


	public boolean equals(Object obj) {
		if(!(obj instanceof CompletedTasksAsn)){
			return false;
		}
		return TYPE.equals(this, obj, CONVERTER);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONVERTER, out);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONVERTER, out);
	}

	public static CompletedTasksAsn der_decode(InputStream in) throws IOException {
		return (CompletedTasksAsn)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONVERTER);
	}


	public final static AsnType TYPE = DistributedFeatureExtraction.type(65545);

	public final static CompositeConverter CONVERTER;

	static {
		CONVERTER = new AnnotationCompositeConverter(CompletedTasksAsn.class);
		//AsnConverter imgtasksConverter = new ListConverter(ImgTaskAsn.CONVERTER);
		//CONVERTER.setComponentConverters(new AsnConverter[] { imgtasksConverter });
	}


}
