/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "DistributedFeatureExtraction"
 */
package DistributedFeatureExtraction;

import java.io.*;
import java.math.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;

public class ImageAsn {

	@Component(0)
	public MatAsn matdata;

	@Component(1)
	public Long imageid;


	public boolean equals(Object obj) {
		if(!(obj instanceof ImageAsn)){
			return false;
		}
		return TYPE.equals(this, obj, CONVERTER);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONVERTER, out);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONVERTER, out);
	}

	public static ImageAsn der_decode(InputStream in) throws IOException {
		return (ImageAsn)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONVERTER);
	}


	public final static AsnType TYPE = DistributedFeatureExtraction.type(65551);

	public final static CompositeConverter CONVERTER;

	static {
		CONVERTER = new AnnotationCompositeConverter(ImageAsn.class);
		AsnConverter matdataConverter = MatAsn.CONVERTER;
		AsnConverter imageidConverter = LongConverter.INSTANCE;
		CONVERTER.setComponentConverters(new AsnConverter[] { matdataConverter, imageidConverter });
	}


}
