/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "DistributedFeatureExtraction"
 */
package DistributedFeatureExtraction;

import java.io.*;
import java.math.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.BitString;

public class MatAsn {

	@Component(0)
	public Long numrows;

	@Component(1)
	public Long numcols;

	@Component(2)
	public BitString data;

	@Component(3)
	public Long type;


	public boolean equals(Object obj) {
		if(!(obj instanceof MatAsn)){
			return false;
		}
		return TYPE.equals(this, obj, CONVERTER);
	}

	public void print(PrintStream out) {
		TYPE.print(this, CONVERTER, out);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONVERTER, out);
	}

	public static MatAsn der_decode(InputStream in) throws IOException {
		return (MatAsn)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONVERTER);
	}


	public final static AsnType TYPE = DistributedFeatureExtraction.type(65547);

	public final static CompositeConverter CONVERTER;

	static {
		CONVERTER = new AnnotationCompositeConverter(MatAsn.class);
		AsnConverter numrowsConverter = LongConverter.INSTANCE;
		AsnConverter numcolsConverter = LongConverter.INSTANCE;
		AsnConverter dataConverter = BitStringConverter.INSTANCE;
		AsnConverter typeConverter = LongConverter.INSTANCE;
		CONVERTER.setComponentConverters(new AsnConverter[] { numrowsConverter, numcolsConverter, dataConverter, typeConverter });
	}


}
